[graph]
all-features = true
targets = [
  "x86_64-pc-windows-msvc",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]

[advisories]
version = 2
yanked = "deny"
unmaintained = "all"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
