export const composeContent = {
  newEyebrow: "新邮件",
  replyEyebrow: "回复邮件",
  title: "撰写邮件",
  sender: "发件账户",
  to: "收件人",
  cc: "抄送",
  bcc: "密送",
  subject: "主题",
  body: "邮件正文",
  addCcBcc: "添加抄送 / 密送",
  saving: "正在保存…",
  saved: "已保存到本地草稿",
  saveFailed: "草稿保存失败，请重试后再关闭。",
  offlineSaved: "当前离线，邮件未发送，已保留为草稿。",
  sending: "正在发送…",
  accepted: "邮箱已接受发送，正在等待已发送确认。",
  rejected: "邮件未发送，请检查收件人或账户状态。",
  unknown: "发送结果可能已提交，请先检查已发送邮件。",
  conflict: "草稿已在其他位置更新，请重新打开。",
  noAccount: "请先连接一个可用的邮箱账户。",
  deleteDraft: "删除草稿",
  deleteConfirm: "确定删除这封本地草稿吗？此操作不会删除邮箱服务器上的邮件。",
  emptySubjectConfirm: "这封邮件没有主题，仍要发送吗？",
  offlineReviewConfirm: "这封草稿曾在离线时尝试发送。请确认已重新检查内容，是否继续发送？",
  close: "关闭写邮件窗口",
  send: "发送",
} as const;
