export const gmailOnboardingCopy = {
  dialogLabel: "连接 Gmail",
  eyebrow: "邮箱账户",
  title: "连接 Gmail",
  introduction: "使用系统浏览器完成 Google 授权。Unimail 不会在页面中显示或保存授权码。",
  privacyNote: "授权完成后，此窗口会自动更新。请勿关闭系统浏览器中的授权页面。",
  close: "关闭 Gmail 连接窗口",
  dismiss: "关闭",
  addAccount: "添加邮箱账户",
  startSetup: "开始设置",
  connect: "连接 Gmail",
  reconnect: "重新连接 Gmail",
  retry: "重新尝试",
  cancel: "取消连接",
  done: "完成",
  refreshing: "正在读取 Gmail 连接状态",
  genericUnavailable: "暂时无法读取 Gmail 连接状态。",
  accountsUnavailable: "暂时无法读取已连接账户。",
  configuredTitle: "Gmail 已准备好连接",
  configuredBody: "点击后会打开系统浏览器，请在 Google 页面中确认授权。",
  unconfiguredTitle: "未配置 Gmail 接入",
  unconfiguredBody: "此安装版本尚未配置 Gmail 客户端 ID，其他本地功能仍可正常使用。",
  waitingTitle: "请在系统浏览器中继续",
  waitingBody: "完成 Google 授权后返回 Unimail；无需复制任何代码或链接。",
  exchangingTitle: "正在完成 Gmail 连接",
  exchangingBody: "正在安全保存账户并准备同步收件箱，请稍候。",
  connectedTitle: "Gmail 已连接",
  connectedBody: "账户已保存，最新收件箱同步即将开始。",
  cancelledTitle: "已取消 Gmail 连接",
  cancelledBody: "账户没有发生更改。需要时可以重新开始。",
  failedTitle: "Gmail 连接未完成",
  connectedAccountsHeading: "已连接账户",
  needsAuthentication: "需要重新连接",
  connected: "连接正常",
  unavailable: "暂不可用",
  viewAccount: "查看 Gmail 账户",
} as const;
