export const mailReaderContent = {
  inboxTitle: "收件箱",
  allAccounts: "全部账户",
  allMessages: "全部",
  unreadMessages: "未读",
  loading: "正在读取本地收件箱…",
  loadingDetail: "正在打开邮件…",
  empty: "收件箱空空如也",
  emptyUnread: "没有未读邮件",
  emptyDescription: "同步完成后，缓存邮件会出现在这里。",
  unavailable: "暂时无法读取本地邮件，请稍后重试。",
  retry: "重新加载",
  loadingMore: "正在加载更多邮件…",
  searchLabel: "搜索邮件",
  searchPlaceholder: "搜索标题、正文或发件人",
  clearSearch: "清除",
  searching: "正在搜索本地邮件…",
  searchUnavailable: "暂时无法搜索本地邮件，请稍后重试。",
  noSearchResults: "没有找到匹配邮件",
  noSearchResultsDescription: "可以尝试更换关键词或邮箱范围。",
  loadingMoreSearch: "正在加载更多搜索结果…",
  selectMessage: "选择一封邮件开始阅读",
  noBody: "这封邮件没有可显示的正文。",
  cached: "显示本地缓存邮件",
  blockedImages: (count: number) => `已阻止 ${String(count)} 张远程图片`,
  showRemoteImages: "显示本邮件图片",
  loadingRemoteImages: "正在安全加载…",
  remoteImagesUnavailable: "无法安全加载这些图片，已继续保持阻止。",
  externalLinks: "邮件中的外部链接",
  unknownSize: "大小未知",
  unnamedAttachment: "未命名附件",
  saveAttachment: "保存",
  preparingDownload: "正在准备…",
  downloadingAttachment: "正在下载",
  attachmentProgress: (progress: number) => `已下载 ${String(progress)}%`,
  cancelDownload: "取消",
  savedAttachment: "已保存",
  downloadCancelled: "下载已取消",
  attachmentFailed: "无法下载附件，请稍后重试。",
} as const;
