export const mailReaderContent = {
  inboxTitle: "收件箱",
  allAccounts: "全部账户",
  allMessages: "全部",
  unreadMessages: "未读",
  loading: "正在读取本地收件箱…",
  loadingDetail: "正在打开邮件…",
  empty: "收件箱空空如也",
  emptyUnread: "没有未读邮件",
  emptyDescription: "同步完成后，缓存邮件会出现在这里。",
  unavailable: "暂时无法读取本地邮件，请稍后重试。",
  retry: "重新加载",
  loadingMore: "正在加载更多邮件…",
  selectMessage: "选择一封邮件开始阅读",
  noBody: "这封邮件没有可显示的正文。",
  cached: "显示本地缓存邮件",
  blockedImages: (count: number) => `已阻止 ${String(count)} 张远程图片`,
  showRemoteImages: "显示本邮件图片",
  loadingRemoteImages: "正在安全加载…",
  remoteImagesUnavailable: "无法安全加载这些图片，已继续保持阻止。",
  externalLinks: "邮件中的外部链接",
} as const;
