// This file is generated by `npm run generate:bindings`. Do not edit it manually.

import { invoke } from "@tauri-apps/api/core";

export type ApplicationInfo = { name: string, version: string, platform: string, capabilities: Array<string>, };

export type CredentialStoreKind = "windows" | "macos" | "unsupported";

export type StorageErrorCode = "credential_store_unavailable" | "database_key_unavailable" | "database_key_invalid" | "database_open_failed" | "cipher_unavailable" | "fts5_unavailable" | "migration_failed" | "storage_busy" | "not_found" | "revision_conflict" | "constraint_violation" | "invalid_data" | "cleanup_pending" | "internal";

export type StorageStatus = { ready: boolean, schemaVersion: number, cipherAvailable: boolean, fts5Available: boolean, credentialStore: CredentialStoreKind, };

export type StorageCommandError = { code: StorageErrorCode, message: string, retryable: boolean, };

export type Provider = "gmail" | "outlook" | "qq" | "netease";

export type AccountAuthState = "connected" | "needs_authentication" | "unavailable";

export type OAuthOnboardingState = "unconfigured" | "idle" | "waiting_for_browser" | "exchanging" | "connected" | "cancelled" | "failed";

export type OAuthOnboardingErrorCode = "not_configured" | "browser_open_failed" | "callback_invalid" | "authorization_denied" | "timed_out" | "cancelled" | "authentication_failed" | "provider_unavailable" | "storage_unavailable" | "internal";

export type OAuthOnboardingCommandError = { provider: Provider, code: OAuthOnboardingErrorCode, message: string, retryable: boolean, };

export type ConnectedAccountSummary = { id: string, provider: Provider, email: string, displayName: string | null, authState: AccountAuthState, };

export type OAuthOnboardingStatus = { provider: Provider, state: OAuthOnboardingState, flowId: string | null, account: ConnectedAccountSummary | null, error: OAuthOnboardingCommandError | null, };

export function applicationInfo(): Promise<unknown> {
  return invoke("application_info");
}

export function storageStatus(): Promise<unknown> {
  return invoke("storage_status");
}

export function oauthOnboardingStatus(provider: Provider): Promise<unknown> {
  return invoke("oauth_onboarding_status", { provider });
}

export function startOauthOnboarding(provider: Provider, accountId: string | null): Promise<unknown> {
  return invoke("start_oauth_onboarding", { provider, accountId });
}

export function cancelOauthOnboarding(provider: Provider, flowId: string): Promise<unknown> {
  return invoke("cancel_oauth_onboarding", { provider, flowId });
}

export function connectedAccounts(): Promise<unknown> {
  return invoke("connected_accounts");
}
