// This file is generated by `npm run generate:bindings`. Do not edit it manually.

import { invoke } from "@tauri-apps/api/core";

export type ApplicationInfo = { name: string, version: string, platform: string, capabilities: Array<string>, };

export function applicationInfo(): Promise<unknown> {
  return invoke("application_info");
}
