// This file is generated by `npm run generate:bindings`. Do not edit it manually.

import { invoke } from "@tauri-apps/api/core";

export type ApplicationInfo = { name: string, version: string, platform: string, capabilities: Array<string>, };

export type CredentialStoreKind = "windows" | "macos" | "unsupported";

export type StorageErrorCode = "credential_store_unavailable" | "database_key_unavailable" | "database_key_invalid" | "database_open_failed" | "cipher_unavailable" | "fts5_unavailable" | "migration_failed" | "storage_busy" | "not_found" | "revision_conflict" | "constraint_violation" | "invalid_data" | "cleanup_pending" | "internal";

export type StorageStatus = { ready: boolean, schemaVersion: number, cipherAvailable: boolean, fts5Available: boolean, credentialStore: CredentialStoreKind, };

export type StorageCommandError = { code: StorageErrorCode, message: string, retryable: boolean, };

export type SecurityStorageDiagnosticsV1 = { ready: boolean, schemaVersion: number | null, cipherAvailable: boolean, fts5Available: boolean, credentialStore: CredentialStoreKind, safeErrorCode: StorageErrorCode | null, };

export type ProviderSecurityDiagnosticsV1 = { provider: Provider, configured: boolean, accountCount: number | null, connectedCount: number | null, reconnectCount: number | null, };

export type SecurityDiagnosticsV1 = { appVersion: string, platform: string, online: boolean, storage: SecurityStorageDiagnosticsV1, providers: Array<ProviderSecurityDiagnosticsV1>, };

export type Provider = "gmail" | "outlook" | "qq" | "netease";

export type AccountAuthState = "connected" | "needs_authentication" | "unavailable";

export type OAuthOnboardingState = "unconfigured" | "idle" | "waiting_for_browser" | "exchanging" | "connected" | "cancelled" | "failed";

export type OAuthOnboardingErrorCode = "not_configured" | "browser_open_failed" | "callback_invalid" | "authorization_denied" | "timed_out" | "cancelled" | "authentication_failed" | "provider_unavailable" | "storage_unavailable" | "internal";

export type OAuthOnboardingCommandError = { provider: Provider, code: OAuthOnboardingErrorCode, message: string, retryable: boolean, };

export type ConnectedAccountSummary = { id: string, provider: Provider, email: string, displayName: string | null, authState: AccountAuthState, };

export type OAuthOnboardingStatus = { provider: Provider, state: OAuthOnboardingState, flowId: string | null, account: ConnectedAccountSummary | null, error: OAuthOnboardingCommandError | null, };

export type AddressRole = "from" | "sender" | "to" | "cc" | "bcc" | "reply_to";

export type MessageDirection = "incoming" | "outgoing";

export type InboxPageRequestV1 = { accountId: string | null, unreadOnly: boolean, cursor: string | null, limit: number, };

export type InboxMessageSummaryV1 = { id: string, accountId: string, mailboxId: string, subject: string | null, snippet: string | null, senderName: string | null, senderAddress: string | null, read: boolean, direction: MessageDirection, sentAtMs: string | null, receivedAtMs: string, hasAttachments: boolean, };

export type InboxPageV1 = { items: Array<InboxMessageSummaryV1>, nextCursor: string | null, };

export type MessageAddressV1 = { role: AddressRole, position: number, displayName: string | null, address: string, };

export type ReaderAttachmentV1 = { id: string, fileName: string | null, mediaType: string, sizeBytes: string | null, contentId: string | null, inline: boolean, };

export type RemoteImageResultV1 = { mediaType: string, dataUrl: string, };

export type MessageDetailV1 = { summary: InboxMessageSummaryV1, threadId: string | null, rfcMessageId: string | null, plainBody: string | null, htmlBody: string | null, parserVersion: number, sanitizerVersion: number, addresses: Array<MessageAddressV1>, attachments: Array<ReaderAttachmentV1>, };

export type AssignReadStateResultV1 = { messageId: string, read: boolean, generation: string, };

export type AttachmentDownloadErrorCode = "attachment_not_found" | "attachment_unavailable" | "account_unavailable" | "offline" | "destination_collision" | "attachment_too_large" | "download_cancelled" | "provider_failed" | "write_failed" | "verification_failed" | "storage_unavailable" | "internal";

export type AttachmentDownloadCommandError = { code: AttachmentDownloadErrorCode, message: string, retryable: boolean, };

export type AttachmentDownloadStateV1 = "downloading" | "completed" | "cancelled" | "failed";

export type AttachmentDownloadSnapshotV1 = { operationId: string, attachmentId: string, state: AttachmentDownloadStateV1, bytesWritten: string, totalBytes: string | null, error: AttachmentDownloadCommandError | null, };

export type SearchPageRequestV1 = { query: string, accountId: string | null, unreadOnly: boolean, cursor: string | null, limit: number, };

export type SearchMessageHitV1 = { summary: InboxMessageSummaryV1, matchContext: string | null, };

export type SearchPageV1 = { items: Array<SearchMessageHitV1>, nextCursor: string | null, };

export type ComposeCommandErrorCode = "invalid_data" | "not_found" | "revision_conflict" | "account_unavailable" | "empty_subject_confirmation_required" | "offline_review_confirmation_required" | "send_locked" | "storage_unavailable" | "internal";

export type ComposeCommandError = { code: ComposeCommandErrorCode, message: string, retryable: boolean, };

export type DraftAddressV1 = { displayName: string | null, address: string, };

export type DraftV1 = { id: string, accountId: string, to: Array<DraftAddressV1>, cc: Array<DraftAddressV1>, bcc: Array<DraftAddressV1>, subject: string, plainBody: string, reply: boolean, revision: string, createdAtMs: string, updatedAtMs: string, offlineReviewRequired: boolean, };

export type DraftSummaryV1 = { id: string, accountId: string, subject: string, recipientCount: number, revision: string, updatedAtMs: string, offlineReviewRequired: boolean, };

export type SaveDraftRequestV1 = { draftId: string | null, accountId: string, to: Array<DraftAddressV1>, cc: Array<DraftAddressV1>, bcc: Array<DraftAddressV1>, subject: string, plainBody: string, expectedRevision: string | null, };

export type ExplicitSendRequestV1 = { draftId: string, draftRevision: string, emptySubjectConfirmed: boolean, offlineReviewConfirmed: boolean, };

export type ExplicitSendStateV1 = "offline_saved" | "accepted_pending" | "rejected" | "unknown_locked";

export type OutboundAttemptState = "submitting" | "accepted_pending" | "reconciled" | "rejected" | "unknown_locked";

export type OutboundFailureCode = "recipient_rejected" | "authentication_required" | "provider_unavailable" | "invalid_draft" | "internal";

export type ExplicitSendResultV1 = { state: ExplicitSendStateV1, draft: DraftV1 | null, attemptId: string | null, errorCode: OutboundFailureCode | null, };

export type SentItemV1 = { attemptId: string, draftId: string, accountId: string, state: OutboundAttemptState, sender: DraftAddressV1, to: Array<DraftAddressV1>, cc: Array<DraftAddressV1>, bcc: Array<DraftAddressV1>, subject: string, plainBody: string, providerObserved: boolean, reconciledMessageId: string | null, canAuthorizeRetry: boolean, retryAuthorized: boolean, updatedAtMs: string, };

export type SentRefreshResultV1 = { accountId: string, updatedAttempts: number, };

export type RetryAuthorizationResultV1 = { attemptId: string, authorized: boolean, };

export function applicationInfo(): Promise<unknown> {
  return invoke("application_info");
}

export function storageStatus(): Promise<unknown> {
  return invoke("storage_status");
}

export function securityDiagnostics(): Promise<unknown> {
  return invoke("security_diagnostics");
}

export function oauthOnboardingStatus(provider: Provider): Promise<unknown> {
  return invoke("oauth_onboarding_status", { provider });
}

export function startOauthOnboarding(provider: Provider, accountId: string | null): Promise<unknown> {
  return invoke("start_oauth_onboarding", { provider, accountId });
}

export function cancelOauthOnboarding(provider: Provider, flowId: string): Promise<unknown> {
  return invoke("cancel_oauth_onboarding", { provider, flowId });
}

export function connectAuthorizationCodeAccount(provider: Provider, accountId: string | null, accountAddress: string, authorizationCode: string): Promise<unknown> {
  return invoke("connect_authorization_code_account", { provider, accountId, accountAddress, authorizationCode });
}

export function connectedAccounts(): Promise<unknown> {
  return invoke("connected_accounts");
}

export function listInboxMessages(request: InboxPageRequestV1): Promise<unknown> {
  return invoke("list_inbox_messages", { request });
}

export function getMessageDetail(messageId: string): Promise<unknown> {
  return invoke("get_message_detail", { messageId });
}

export function assignMessageReadState(messageId: string, read: boolean): Promise<unknown> {
  return invoke("assign_message_read_state", { messageId, read });
}

export function searchInboxMessages(request: SearchPageRequestV1): Promise<unknown> {
  return invoke("search_inbox_messages", { request });
}

export function beginAttachmentDownload(attachmentId: string): Promise<unknown> {
  return invoke("begin_attachment_download", { attachmentId });
}

export function getAttachmentDownloadStatus(operationId: string): Promise<unknown> {
  return invoke("get_attachment_download_status", { operationId });
}

export function cancelAttachmentDownload(operationId: string): Promise<unknown> {
  return invoke("cancel_attachment_download", { operationId });
}

export function listDrafts(accountId: string | null): Promise<unknown> {
  return invoke("list_drafts", { accountId });
}

export function getDraft(draftId: string): Promise<unknown> {
  return invoke("get_draft", { draftId });
}

export function saveDraft(request: SaveDraftRequestV1): Promise<unknown> {
  return invoke("save_draft", { request });
}

export function deleteDraft(draftId: string): Promise<unknown> {
  return invoke("delete_draft", { draftId });
}

export function createReplyDraft(messageId: string): Promise<unknown> {
  return invoke("create_reply_draft", { messageId });
}

export function sendDraft(request: ExplicitSendRequestV1): Promise<unknown> {
  return invoke("send_draft", { request });
}

export function listSentItems(accountId: string | null): Promise<unknown> {
  return invoke("list_sent_items", { accountId });
}

export function refreshSentItems(accountId: string): Promise<unknown> {
  return invoke("refresh_sent_items", { accountId });
}

export function authorizeOutboundRetry(attemptId: string): Promise<unknown> {
  return invoke("authorize_outbound_retry", { attemptId });
}

export function reportConnectivity(online: boolean): Promise<unknown> {
  return invoke("report_connectivity", { online });
}

export function fetchMessageRemoteImage(messageId: string, url: string): Promise<unknown> {
  return invoke("fetch_message_remote_image", { messageId, url });
}

export function openConfirmedExternalUrl(url: string): Promise<unknown> {
  return invoke("open_confirmed_external_url", { url });
}
